# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9ab6341575b8454a3959d0514a965d518b2705e0ce12eeb95a1059f4a6e305b8fa045b52c08345f4f6e15c35bcfaee0693b1b99e3a628df3bbfaf10f1447a8

test:
  secret_key_base: d9c94c16707d007b6a3246dec88c2060d7d885fd4a3a9cba7f20fd4cfecfad9a591def28e69b74068a5ae1bb8e0a37eb911d6bce1c5258bd2498054ab290b2b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
